/*CREATE OR ALTER PROCEDURE SHOWEMPDATA
AS
BEGIN
SELECT AVG(SALARY)AS [AVARAGE SALARY] FROM EMPLOYEES
END
EXEC SHOWEMPDATA*/

CREATE OR ALTER PROCEDURE SHOWEMPWITHID(@employee_id int)
AS
BEGIN
SELECT * FROM EMPLOYEES where employee_id =@employee_id
END
EXEC SHOWEMPWITHID 601
