CREATE OR ALTER PROCEDURE GETSAL
@EMPOLYEE_ID INT , @SALARY MONEY OUTPUT
AS 
BEGIN
SELECT @SALARY=SALARY FROM EMPLOYEES WHERE  EMPLOYEE_ID=@EMPOLYEE_ID
END
/*REFRESH DB PROGRAMMABILITY SP EXECUTE SP  VALUE NULL*/