//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BanTB()
        {
            this.BanTB1 = new HashSet<BanTB>();
        }
    
        public int accotNo { get; set; }
        public string acct_holder_name { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<int> Ref_acno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanTB> BanTB1 { get; set; }
        public virtual BanTB BanTB2 { get; set; }
    }
}
